pr: none # will disable PR builds entirely

trigger:
- master
- feature/*

stages:
- stage: Build
  displayName: Build

  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@2  
      displayName: Install WYAM
      inputs:
        command: custom
        custom: tool
        arguments: install --tool-path . Wyam.Tool
    - script: wyam
      displayName: Build

- stage: Deploy
  displayName: Deploy
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) # this will only run on master
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - script: build -target Deploy
            displayName: Deploy To Production
            env:
              NETLIFY_TOKEN: $(NETLIFY_TOKEN)
              NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)