BEGIN TRANSACTION;

CREATE TABLE Tag (
    Id INTEGER NOT NULL CONSTRAINT PK_Tag PRIMARY KEY AUTOINCREMENT,
    Description TEXT
);

CREATE TABLE PostTag (
    Id INTEGER NOT NULL CONSTRAINT PK_PostTag PRIMARY KEY AUTOINCREMENT,
    PostId INTEGER NOT NULL,
    TagId INTEGER NOT NULL,
    CONSTRAINT FK_PostTag_Post_PostId FOREIGN KEY (PostId) REFERENCES Post (Id) ON DELETE CASCADE,
    CONSTRAINT FK_PostTag_Tag_TagId FOREIGN KEY (TagId) REFERENCES Tag (Id) ON DELETE CASCADE
);

CREATE TABLE PostContent (
    Id INTEGER NOT NULL CONSTRAINT PK_PostContent PRIMARY KEY AUTOINCREMENT,
    Content TEXT,
    PostId INTEGER NOT NULL,
    CONSTRAINT FK_PostContent_Post_PostId FOREIGN KEY (PostId) REFERENCES Post (Id) ON DELETE CASCADE
);

CREATE TABLE Post (
    Id INTEGER NOT NULL CONSTRAINT PK_Post PRIMARY KEY AUTOINCREMENT,
    Author TEXT,
    Created TEXT,
    Description TEXT,
    Published TEXT,
    Title TEXT
);

CREATE TABLE Comment (
    Id INTEGER NOT NULL CONSTRAINT PK_Comment PRIMARY KEY AUTOINCREMENT,
    Content TEXT,
    Created TEXT NOT NULL,
    Email TEXT,
    Name TEXT,
    PostId INTEGER NOT NULL,
    CONSTRAINT FK_Comment_Post_PostId FOREIGN KEY (PostId) REFERENCES Post (Id) ON DELETE CASCADE
);

CREATE INDEX IX_PostTag_TagId ON PostTag (TagId);
CREATE INDEX IX_PostTag_PostId ON PostTag (PostId);
CREATE UNIQUE INDEX IX_PostContent_PostId ON PostContent (PostId);
CREATE INDEX IX_Comment_PostId ON Comment (PostId);

COMMIT;
